name: ict602
description: A mobile application for ICT602 Carry Marks management
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Database packages
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0  # Untuk Windows/Linux/Mac support
  path: ^1.8.3
  
  # Other dependencies
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true